markdown: rdiscount
pygments: true

permalink: /:title/
url: http://janseon.github.io
name: Janseon
author: Janseon
qq:
email: janseon@gmail.com
github: janseon
duoshuo: janseon
beian:
cnblogs:
cnzz:
weibo: janseon

gems: [jekyll-paginate]
paginate: 20
truncate: true
about: "大兴兴 (Janseon)"



